"""Find code addresses the game can call indirectly that XenonRecomp doesn't
know as function starts: addresses stored in data sections, and addresses
materialised in code with lis + addi/ori. Excludes jump-table labels and
known function starts. Keeps only "entry-like" targets (preceded by blr, an
unconditional b, or padding), i.e. secondary entry points that share a body
with a neighbouring function.

    python3 survey/find_entry_points.py        # report
"""
import bisect, re, struct, tomllib, sys
exec(open('survey/classify_switches.py').read().split("tables = sorted")[0])

# Function starts XenonRecomp knows, minus previously configured secondary
# entries (they appear in the mapping too), so reruns give the same answer.
_cfg = open('config/nfsmw.toml').read()
_configured = set(int(x, 16) for x in re.findall(r'0x([0-9A-F]+)', _cfg.split('secondary_entries = [')[1].split(']')[0])) \
    if 'secondary_entries = [' in _cfg else set()
fnstarts = set(int(x, 16) for x in re.findall(r'\{ 0x([0-9A-F]+),', open('ppc/ppc_func_mapping.cpp').read())) - _configured
labels = set()
for t in tomllib.load(open('config/switch_tables.toml', 'rb'))['switch']:
    labels |= set(t['labels'])

def is_code(v):
    return TEXT[0] <= v < TEXT[1] and v % 4 == 0

refs = {}
for lo, hi in [(0x82000600, 0x820B106C), (0x828D0000, 0x82C8CE8C)]:
    for a in range(lo, hi, 4):
        v = word(a)
        if is_code(v):
            refs.setdefault(v, set()).add(('data', a))

# lis rD,hi ; ... addi/ori rX,rD,lo within the next 8 instructions
for a in range(TEXT[0], TEXT[1], 4):
    w = word(a)
    if w >> 26 != 15 or (w >> 16) & 31 != 0:      # lis = addis rD,0,imm
        continue
    rd = (w >> 21) & 31
    hi = (w & 0xFFFF) << 16
    for b in range(a + 4, min(a + 36, TEXT[1]), 4):
        x = word(b)
        op = x >> 26
        if op in (14, 24) and (x >> 16) & 31 == rd:  # addi / ori with rA = rD
            lo = x & 0xFFFF
            v = (hi + (lo - 0x10000 if op == 14 and lo & 0x8000 else lo)) & 0xFFFFFFFF
            if is_code(v):
                refs.setdefault(v, set()).add(('code', a))
            break
        if (x >> 21) & 31 == rd and op not in (36, 37, 32, 33):  # rD overwritten
            break

def entry_like(v):
    p = word(v - 4)
    return p == 0x4E800020 or p == 0 or (p >> 26 == 18 and p & 3 == 0)

cand = sorted(v for v in refs if v not in fnstarts and v not in labels and entry_like(v))
print(f'{len(refs)} referenced code addresses; {len(cand)} entry-like and not function starts', file=sys.stderr)
lines = []
for v in cand:
    kinds = sorted(set(k for k, _ in refs[v]))
    i = bisect.bisect_right(starts, v) - 1
    inside = funcs[i][0] <= v < funcs[i][1]
    note = f'in .pdata fn 0x{funcs[i][0]:08X}' if inside else 'leaf code'
    lines.append(f'    0x{v:08X},  # referenced from {"+".join(kinds)}; {note}')
    print(lines[-1], file=sys.stderr)

if '--write' in sys.argv:
    MARKER = '# --- generated by survey/find_entry_points.py --write ---'
    text = open('config/nfsmw.toml').read().split(MARKER)[0].rstrip()
    # The block has to sit in [main] with the other keys, so insert it before
    # the leaf-bounds block if present, else append.
    block = (MARKER + '\n# Secondary entry points: code addresses the game calls through pointers\n'
             '# that lie inside another function. Do not edit by hand; rerun.\n'
             'secondary_entries = [\n' + '\n'.join(lines) + '\n]\n# --- end find_entry_points ---\n')
    if '# --- end find_entry_points ---' in open('config/nfsmw.toml').read():
        full = open('config/nfsmw.toml').read()
        before = full.split(MARKER)[0]
        after = full.split('# --- end find_entry_points ---\n')[1]
        open('config/nfsmw.toml', 'w').write(before + block + after)
    else:
        leaf = '# --- generated by survey/leaf_switch_bounds.py'
        full = open('config/nfsmw.toml').read()
        i = full.index(leaf)
        open('config/nfsmw.toml', 'w').write(full[:i] + block + '\n' + full[i:])
    print('wrote config/nfsmw.toml', file=sys.stderr)
