# Generated by tests/gen_instr_tests.py (independent Python model). Do not edit.

test_nfsmw_vcmpgtsh_rc_1:
  #_ REGISTER_IN v4 [281B048D, 347BFA24, 64260380, 0BC9DA6D]
  #_ REGISTER_IN v5 [E6EC99E6, 2DF601F9, C5A26A4C, F990B0D7]
  #_ REGISTER_IN r3 0
  vcmpgtsh. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [FFFFFFFF, FFFF0000, FFFF0000, FFFFFFFF]
  #_ REGISTER_OUT r3 0

test_nfsmw_vcmpgtsh_rc_2:
  #_ REGISTER_IN v4 [60EB86C4, 7FFF9BF8, 80007FFF, 80005CA7]
  #_ REGISTER_IN v5 [B3815C98, CA205D46, FE6B7FFF, 45E20000]
  #_ REGISTER_IN r3 0
  vcmpgtsh. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [FFFF0000, FFFF0000, 00000000, 0000FFFF]
  #_ REGISTER_OUT r3 0

test_nfsmw_vcmpgtsh_rc_3:
  #_ REGISTER_IN v4 [FFFFFFFF, 2127CEFC, 8A27730A, 000080F4]
  #_ REGISTER_IN v5 [80370001, B274E6AC, 7826FFFF, C35C4DFA]
  #_ REGISTER_IN r3 0
  vcmpgtsh. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [FFFF0000, FFFF0000, 0000FFFF, FFFF0000]
  #_ REGISTER_OUT r3 0

test_nfsmw_vcmpgtsh_rc_4:
  #_ REGISTER_IN v4 [04418000, 0F4BFFFF, 80003E22, 800038ED]
  #_ REGISTER_IN v5 [B0007FFF, 00008000, 2C310001, 8000266D]
  #_ REGISTER_IN r3 0
  vcmpgtsh. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [FFFF0000, FFFFFFFF, 0000FFFF, 0000FFFF]
  #_ REGISTER_OUT r3 0

test_nfsmw_vcmpgtsh_rc_5:
  #_ REGISTER_IN v4 [0001818A, 8000086B, FFFF8000, 000081E0]
  #_ REGISTER_IN v5 [0001818A, 8000086B, FFFF8000, 000081E0]
  #_ REGISTER_IN r3 0
  vcmpgtsh. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_OUT r3 2

test_nfsmw_vcmpgtsh_rc_6:
  #_ REGISTER_IN v4 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_IN v5 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_IN r3 0
  vcmpgtsh. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_OUT r3 2

test_nfsmw_vcmpgtsh_rc_7:
  #_ REGISTER_IN v4 [7FFF7FFF, 7FFF7FFF, 7FFF7FFF, 7FFF7FFF]
  #_ REGISTER_IN v5 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_IN r3 0
  vcmpgtsh. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [FFFFFFFF, FFFFFFFF, FFFFFFFF, FFFFFFFF]
  #_ REGISTER_OUT r3 1

test_nfsmw_vcmpgtsh_rc_8:
  #_ REGISTER_IN v4 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_IN v5 [7FFF7FFF, 7FFF7FFF, 7FFF7FFF, 7FFF7FFF]
  #_ REGISTER_IN r3 0
  vcmpgtsh. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_OUT r3 2

