# Generated by tests/gen_instr_tests.py (independent Python model). Do not edit.

test_nfsmw_vspltish_1:
  vspltish v3, -16
  blr
  #_ REGISTER_OUT v3 [FFF0FFF0, FFF0FFF0, FFF0FFF0, FFF0FFF0]

test_nfsmw_vspltish_2:
  vspltish v3, -1
  blr
  #_ REGISTER_OUT v3 [FFFFFFFF, FFFFFFFF, FFFFFFFF, FFFFFFFF]

test_nfsmw_vspltish_3:
  vspltish v3, 0
  blr
  #_ REGISTER_OUT v3 [00000000, 00000000, 00000000, 00000000]

test_nfsmw_vspltish_4:
  vspltish v3, 1
  blr
  #_ REGISTER_OUT v3 [00010001, 00010001, 00010001, 00010001]

test_nfsmw_vspltish_5:
  vspltish v3, 7
  blr
  #_ REGISTER_OUT v3 [00070007, 00070007, 00070007, 00070007]

test_nfsmw_vspltish_6:
  vspltish v3, 15
  blr
  #_ REGISTER_OUT v3 [000F000F, 000F000F, 000F000F, 000F000F]

