# Generated by tests/gen_instr_tests.py (independent Python model). Do not edit.

test_nfsmw_bso_1:
  #_ REGISTER_IN f1 1.0
  #_ REGISTER_IN f2 2.0
  #_ REGISTER_IN r3 1
  fcmpu cr1, f1, f2
  bso cr1, .+8
  li r3, 2
  blr
  #_ REGISTER_OUT r3 2

test_nfsmw_bso_2:
  #_ REGISTER_IN f1 1.0
  #_ REGISTER_IN f2 0x7FF8000000000000
  #_ REGISTER_IN r3 1
  fcmpu cr1, f1, f2
  bso cr1, .+8
  li r3, 2
  blr
  #_ REGISTER_OUT r3 1

test_nfsmw_bso_3:
  #_ REGISTER_IN f1 1.0
  #_ REGISTER_IN f2 1.0
  #_ REGISTER_IN r3 1
  fcmpu cr1, f1, f2
  bso cr1, .+8
  li r3, 2
  blr
  #_ REGISTER_OUT r3 2

test_nfsmw_bso_4:
  #_ REGISTER_IN f1 1.0
  #_ REGISTER_IN f2 2.0
  #_ REGISTER_IN r3 1
  fcmpu cr1, f1, f2
  bns cr1, .+8
  li r3, 2
  blr
  #_ REGISTER_OUT r3 1

test_nfsmw_bso_5:
  #_ REGISTER_IN f1 1.0
  #_ REGISTER_IN f2 0x7FF8000000000000
  #_ REGISTER_IN r3 1
  fcmpu cr1, f1, f2
  bns cr1, .+8
  li r3, 2
  blr
  #_ REGISTER_OUT r3 2

test_nfsmw_bso_6:
  #_ REGISTER_IN f1 1.0
  #_ REGISTER_IN f2 1.0
  #_ REGISTER_IN r3 1
  fcmpu cr1, f1, f2
  bns cr1, .+8
  li r3, 2
  blr
  #_ REGISTER_OUT r3 1

test_nfsmw_bso_7:
  #_ REGISTER_IN f1 1.0
  #_ REGISTER_IN f2 2.0
  #_ REGISTER_IN r3 1
  fcmpu cr1, f1, f2
  bsolr cr1
  li r3, 2
  blr
  #_ REGISTER_OUT r3 2

test_nfsmw_bso_8:
  #_ REGISTER_IN f1 1.0
  #_ REGISTER_IN f2 0x7FF8000000000000
  #_ REGISTER_IN r3 1
  fcmpu cr1, f1, f2
  bsolr cr1
  li r3, 2
  blr
  #_ REGISTER_OUT r3 1

test_nfsmw_bso_9:
  #_ REGISTER_IN f1 1.0
  #_ REGISTER_IN f2 2.0
  #_ REGISTER_IN r3 1
  fcmpu cr1, f1, f2
  bnslr cr1
  li r3, 2
  blr
  #_ REGISTER_OUT r3 1

test_nfsmw_bso_10:
  #_ REGISTER_IN f1 1.0
  #_ REGISTER_IN f2 0x7FF8000000000000
  #_ REGISTER_IN r3 1
  fcmpu cr1, f1, f2
  bnslr cr1
  li r3, 2
  blr
  #_ REGISTER_OUT r3 2

