# Generated by tests/gen_instr_tests.py (independent Python model). Do not edit.

test_nfsmw_cror_1:
  #_ REGISTER_IN r4 0xFFFFFFFFFFFFFFFF
  #_ REGISTER_IN r5 0x1
  #_ REGISTER_IN r3 1
  cmpwi cr0, r4, 0
  cmpwi cr1, r5, 0
  cmpwi cr7, r5, 12345
  cror 30, 0, 5
  beq cr7, .+8
  li r3, 2
  blr
  #_ REGISTER_OUT r3 1

test_nfsmw_cror_2:
  #_ REGISTER_IN r4 0xFFFFFFFFFFFFFFFF
  #_ REGISTER_IN r5 0xFFFFFFFFFFFFFFFF
  #_ REGISTER_IN r3 1
  cmpwi cr0, r4, 0
  cmpwi cr1, r5, 0
  cmpwi cr7, r5, 12345
  cror 30, 0, 5
  beq cr7, .+8
  li r3, 2
  blr
  #_ REGISTER_OUT r3 1

test_nfsmw_cror_3:
  #_ REGISTER_IN r4 0x1
  #_ REGISTER_IN r5 0x1
  #_ REGISTER_IN r3 1
  cmpwi cr0, r4, 0
  cmpwi cr1, r5, 0
  cmpwi cr7, r5, 12345
  cror 30, 0, 5
  beq cr7, .+8
  li r3, 2
  blr
  #_ REGISTER_OUT r3 1

test_nfsmw_cror_4:
  #_ REGISTER_IN r4 0x1
  #_ REGISTER_IN r5 0xFFFFFFFFFFFFFFFF
  #_ REGISTER_IN r3 1
  cmpwi cr0, r4, 0
  cmpwi cr1, r5, 0
  cmpwi cr7, r5, 12345
  cror 30, 0, 5
  beq cr7, .+8
  li r3, 2
  blr
  #_ REGISTER_OUT r3 2

test_nfsmw_cror_5:
  #_ REGISTER_IN r4 0xFFFFFFFFFFFFFFFF
  #_ REGISTER_IN r5 0x1
  #_ REGISTER_IN r3 1
  cmpwi cr0, r4, 0
  cmpwi cr1, r5, 0
  cmpwi cr7, r5, 12345
  crorc 30, 0, 5
  beq cr7, .+8
  li r3, 2
  blr
  #_ REGISTER_OUT r3 1

test_nfsmw_cror_6:
  #_ REGISTER_IN r4 0xFFFFFFFFFFFFFFFF
  #_ REGISTER_IN r5 0xFFFFFFFFFFFFFFFF
  #_ REGISTER_IN r3 1
  cmpwi cr0, r4, 0
  cmpwi cr1, r5, 0
  cmpwi cr7, r5, 12345
  crorc 30, 0, 5
  beq cr7, .+8
  li r3, 2
  blr
  #_ REGISTER_OUT r3 1

test_nfsmw_cror_7:
  #_ REGISTER_IN r4 0x1
  #_ REGISTER_IN r5 0x1
  #_ REGISTER_IN r3 1
  cmpwi cr0, r4, 0
  cmpwi cr1, r5, 0
  cmpwi cr7, r5, 12345
  crorc 30, 0, 5
  beq cr7, .+8
  li r3, 2
  blr
  #_ REGISTER_OUT r3 2

test_nfsmw_cror_8:
  #_ REGISTER_IN r4 0x1
  #_ REGISTER_IN r5 0xFFFFFFFFFFFFFFFF
  #_ REGISTER_IN r3 1
  cmpwi cr0, r4, 0
  cmpwi cr1, r5, 0
  cmpwi cr7, r5, 12345
  crorc 30, 0, 5
  beq cr7, .+8
  li r3, 2
  blr
  #_ REGISTER_OUT r3 1

