# Generated by tests/gen_instr_tests.py (independent Python model). Do not edit.

test_nfsmw_vcmpgtsw_rc_1:
  #_ REGISTER_IN v4 [067A09E2, DBFC34B9, 1D0C727C, C1ADEECD]
  #_ REGISTER_IN v5 [8632FF96, E477A6EB, 038FFD4F, 6C113843]
  #_ REGISTER_IN r3 0
  vcmpgtsw. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [FFFFFFFF, 00000000, FFFFFFFF, 00000000]
  #_ REGISTER_OUT r3 0

test_nfsmw_vcmpgtsw_rc_2:
  #_ REGISTER_IN v4 [8A3DFF64, 00000000, F085B6A4, A18719A9]
  #_ REGISTER_IN v5 [EA66617F, 7FFFFFFF, 7FFFFFFF, 4013A59D]
  #_ REGISTER_IN r3 0
  vcmpgtsw. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_OUT r3 2

test_nfsmw_vcmpgtsw_rc_3:
  #_ REGISTER_IN v4 [0C6EE45E, F582BBDE, ECCE0A0E, E606FA23]
  #_ REGISTER_IN v5 [40FCB85E, D2F91994, 228141A5, 00000001]
  #_ REGISTER_IN r3 0
  vcmpgtsw. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [00000000, FFFFFFFF, 00000000, 00000000]
  #_ REGISTER_OUT r3 0

test_nfsmw_vcmpgtsw_rc_4:
  #_ REGISTER_IN v4 [D8271C51, 10866472, CB170760, 47852AFA]
  #_ REGISTER_IN v5 [123BDB78, 00000000, 80000000, FE0C5B7C]
  #_ REGISTER_IN r3 0
  vcmpgtsw. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [00000000, FFFFFFFF, FFFFFFFF, FFFFFFFF]
  #_ REGISTER_OUT r3 0

test_nfsmw_vcmpgtsw_rc_5:
  #_ REGISTER_IN v4 [574FBCF8, CFBC5D06, B71274A4, C5C67076]
  #_ REGISTER_IN v5 [574FBCF8, CFBC5D06, B71274A4, C5C67076]
  #_ REGISTER_IN r3 0
  vcmpgtsw. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_OUT r3 2

test_nfsmw_vcmpgtsw_rc_6:
  #_ REGISTER_IN v4 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_IN v5 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_IN r3 0
  vcmpgtsw. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_OUT r3 2

test_nfsmw_vcmpgtsw_rc_7:
  #_ REGISTER_IN v4 [7FFFFFFF, 7FFFFFFF, 7FFFFFFF, 7FFFFFFF]
  #_ REGISTER_IN v5 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_IN r3 0
  vcmpgtsw. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [FFFFFFFF, FFFFFFFF, FFFFFFFF, FFFFFFFF]
  #_ REGISTER_OUT r3 1

test_nfsmw_vcmpgtsw_rc_8:
  #_ REGISTER_IN v4 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_IN v5 [7FFFFFFF, 7FFFFFFF, 7FFFFFFF, 7FFFFFFF]
  #_ REGISTER_IN r3 0
  vcmpgtsw. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_OUT r3 2

