# Generated by tests/gen_instr_tests.py (independent Python model). Do not edit.

test_nfsmw_vcmpgtuh_rc_1:
  #_ REGISTER_IN v4 [8A7B1994, 71149F7D, 245D8000, 0CD5380E]
  #_ REGISTER_IN v5 [B1ADCE0E, B95BAB5A, 68923479, E4CC5297]
  #_ REGISTER_IN r3 0
  vcmpgtuh. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [00000000, 00000000, 0000FFFF, 00000000]
  #_ REGISTER_OUT r3 0

test_nfsmw_vcmpgtuh_rc_2:
  #_ REGISTER_IN v4 [42F60B01, 0001FFFF, 00003F8D, 00007FFF]
  #_ REGISTER_IN v5 [229D068B, 8DD860FF, D9236482, 5E09C59B]
  #_ REGISTER_IN r3 0
  vcmpgtuh. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [FFFFFFFF, 0000FFFF, 00000000, 00000000]
  #_ REGISTER_OUT r3 0

test_nfsmw_vcmpgtuh_rc_3:
  #_ REGISTER_IN v4 [517DD672, 0001E6FF, 225D8BBD, 00000000]
  #_ REGISTER_IN v5 [DD362B28, E1870000, F5760000, 8000B5AF]
  #_ REGISTER_IN r3 0
  vcmpgtuh. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [0000FFFF, 0000FFFF, 0000FFFF, 00000000]
  #_ REGISTER_OUT r3 0

test_nfsmw_vcmpgtuh_rc_4:
  #_ REGISTER_IN v4 [8000FFFF, B7A24515, CA34E48C, 1221D2B9]
  #_ REGISTER_IN v5 [E429B443, 5573A288, 974DC712, 0353D80C]
  #_ REGISTER_IN r3 0
  vcmpgtuh. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [0000FFFF, FFFF0000, FFFFFFFF, FFFF0000]
  #_ REGISTER_OUT r3 0

test_nfsmw_vcmpgtuh_rc_5:
  #_ REGISTER_IN v4 [95810000, 7FFF6BB8, 0001044B, 00008000]
  #_ REGISTER_IN v5 [95810000, 7FFF6BB8, 0001044B, 00008000]
  #_ REGISTER_IN r3 0
  vcmpgtuh. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_OUT r3 2

test_nfsmw_vcmpgtuh_rc_6:
  #_ REGISTER_IN v4 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_IN v5 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_IN r3 0
  vcmpgtuh. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_OUT r3 2

test_nfsmw_vcmpgtuh_rc_7:
  #_ REGISTER_IN v4 [7FFF7FFF, 7FFF7FFF, 7FFF7FFF, 7FFF7FFF]
  #_ REGISTER_IN v5 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_IN r3 0
  vcmpgtuh. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [FFFFFFFF, FFFFFFFF, FFFFFFFF, FFFFFFFF]
  #_ REGISTER_OUT r3 1

test_nfsmw_vcmpgtuh_rc_8:
  #_ REGISTER_IN v4 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_IN v5 [7FFF7FFF, 7FFF7FFF, 7FFF7FFF, 7FFF7FFF]
  #_ REGISTER_IN r3 0
  vcmpgtuh. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_OUT r3 2

