# Generated by tests/gen_instr_tests.py (independent Python model). Do not edit.

test_nfsmw_stfsu_1:
  #_ REGISTER_IN f1 1.5
  #_ REGISTER_IN r4 0x1000
  stfsu f1, 16(r4)
  blr
  #_ REGISTER_OUT r4 0x1010
  #_ MEMORY_OUT 00001010 3F C0 00 00

test_nfsmw_stfsu_2:
  #_ REGISTER_IN f1 -2.25
  #_ REGISTER_IN r4 0x1000
  stfsu f1, 0(r4)
  blr
  #_ REGISTER_OUT r4 0x1000
  #_ MEMORY_OUT 00001000 C0 10 00 00

test_nfsmw_stfsu_3:
  #_ REGISTER_IN f1 3.0e38
  #_ REGISTER_IN r4 0x1000
  stfsu f1, -8(r4)
  blr
  #_ REGISTER_OUT r4 0xFF8
  #_ MEMORY_OUT 00000FF8 7F 61 B1 E6

