# Generated by tests/gen_instr_tests.py (independent Python model). Do not edit.

test_nfsmw_vcmpequh_rc_1:
  #_ REGISTER_IN v4 [DFE17FFF, E18C476B, FFFF2F87, FE218000]
  #_ REGISTER_IN v5 [FD5FE652, 1C14F3CD, 808D69A2, F3A869B7]
  #_ REGISTER_IN r3 0
  vcmpequh. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_OUT r3 2

test_nfsmw_vcmpequh_rc_2:
  #_ REGISTER_IN v4 [D17D7789, 7FFF7FFF, 40A8A870, 372CC452]
  #_ REGISTER_IN v5 [9C217FFF, 0001FFFF, D76E723B, FFFF8000]
  #_ REGISTER_IN r3 0
  vcmpequh. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_OUT r3 2

test_nfsmw_vcmpequh_rc_3:
  #_ REGISTER_IN v4 [1DBAFEB3, 1A17E7EA, C9567C3A, 7BEE49BF]
  #_ REGISTER_IN v5 [FFFF6B8F, 7C676E6A, F74E54AD, 80000000]
  #_ REGISTER_IN r3 0
  vcmpequh. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_OUT r3 2

test_nfsmw_vcmpequh_rc_4:
  #_ REGISTER_IN v4 [3CE84406, 4A5F2D7B, 00010F1F, C7C3E7EB]
  #_ REGISTER_IN v5 [D59CF5B0, 00000001, 00015BA4, C0470001]
  #_ REGISTER_IN r3 0
  vcmpequh. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [00000000, 00000000, FFFF0000, 00000000]
  #_ REGISTER_OUT r3 0

test_nfsmw_vcmpequh_rc_5:
  #_ REGISTER_IN v4 [EB5FB56A, F8FBBBEB, F1A9D7CC, 0000A354]
  #_ REGISTER_IN v5 [EB5FB56A, F8FBBBEB, F1A9D7CC, 0000A354]
  #_ REGISTER_IN r3 0
  vcmpequh. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [FFFFFFFF, FFFFFFFF, FFFFFFFF, FFFFFFFF]
  #_ REGISTER_OUT r3 1

test_nfsmw_vcmpequh_rc_6:
  #_ REGISTER_IN v4 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_IN v5 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_IN r3 0
  vcmpequh. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [FFFFFFFF, FFFFFFFF, FFFFFFFF, FFFFFFFF]
  #_ REGISTER_OUT r3 1

test_nfsmw_vcmpequh_rc_7:
  #_ REGISTER_IN v4 [7FFF7FFF, 7FFF7FFF, 7FFF7FFF, 7FFF7FFF]
  #_ REGISTER_IN v5 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_IN r3 0
  vcmpequh. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_OUT r3 2

test_nfsmw_vcmpequh_rc_8:
  #_ REGISTER_IN v4 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_IN v5 [7FFF7FFF, 7FFF7FFF, 7FFF7FFF, 7FFF7FFF]
  #_ REGISTER_IN r3 0
  vcmpequh. v3, v4, v5
  bge cr6, .+8
  ori r3, r3, 1
  bne cr6, .+8
  ori r3, r3, 2
  blr
  #_ REGISTER_OUT v3 [00000000, 00000000, 00000000, 00000000]
  #_ REGISTER_OUT r3 2

