# SpeedBreaker. GPL-3.0-or-later (see COPYING).
#
#   cmake -DSOURCE_DIR=<repo> -DOUTPUT=<file> -DVERSION=<x.y.z> [-DBUILD_TYPE=Release] -P build_info.cmake
#
# Writes the build's identity for report/build_info.cpp: the version (the
# top-level project(), passed in), the git commit, whether tracked files
# differ from it, and when it was built. It runs on
# every build (runtime/CMakeLists.txt) but rewrites OUTPUT, which bumps the
# build date and relinks, only when the identity changed (another commit,
# another diff, another build type, another version): a no-op build stays a
# no-op.
if(NOT VERSION)
    set(VERSION "0.0.0")
endif()
set(commit "unknown")
set(dirty 0)
set(diff_hash "")
find_package(Git QUIET)
if(GIT_FOUND)
    execute_process(COMMAND ${GIT_EXECUTABLE} -C ${SOURCE_DIR} rev-parse --short HEAD
        OUTPUT_VARIABLE out RESULT_VARIABLE result ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(result EQUAL 0 AND NOT out STREQUAL "")
        set(commit ${out})
        # Changes to tracked files, and new files where the build globs its
        # sources (by name only; scratch files elsewhere in a checkout aren't
        # built).
        execute_process(COMMAND ${GIT_EXECUTABLE} -C ${SOURCE_DIR} diff HEAD --no-ext-diff --no-color
            OUTPUT_VARIABLE diff RESULT_VARIABLE result ERROR_QUIET)
        execute_process(COMMAND ${GIT_EXECUTABLE} -C ${SOURCE_DIR} ls-files --others --exclude-standard -- runtime recomp
            OUTPUT_VARIABLE untracked ERROR_QUIET)
        if(result EQUAL 0 AND NOT "${diff}${untracked}" STREQUAL "")
            set(dirty 1)
            string(SHA1 diff_hash "${diff}${untracked}")
        endif()
    endif()
endif()

set(identity "${VERSION} ${commit} ${dirty} ${diff_hash} ${BUILD_TYPE}")
if(EXISTS ${OUTPUT})
    file(STRINGS ${OUTPUT} previous REGEX "^// identity: ")
    if(previous STREQUAL "// identity: ${identity}")
        return()
    endif()
endif()

string(TIMESTAMP date "%Y-%m-%d %H:%M UTC" UTC)
file(WRITE ${OUTPUT}
"// Generated by runtime/report/build_info.cmake at build time. Do not edit.
// identity: ${identity}
#define NFSMW_BUILD_VERSION \"${VERSION}\"
#define NFSMW_BUILD_COMMIT \"${commit}\"
#define NFSMW_BUILD_DIRTY ${dirty}
#define NFSMW_BUILD_DATE \"${date}\"
#define NFSMW_BUILD_TYPE \"${BUILD_TYPE}\"
")
